### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by NarenBabuR** [krasserm/face-recognition#9] opened 2018-08-28 05:30 UTC
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a6c74386105b> in <module>()
      5     img = align_image(img)
      6     # scale RGB values to interval [0,1]
----> 7     img = (img / 255.).astype(np.float32)
      8     # obtain embedding vector for image
      9     #embedded[i] = nn4_small2_pretrained.predict(np.expand_dims(img, axis=0))[0]

**Comment by krasserm** [comment] 2018-08-28 06:53
That's a duplicate of #8

**Closed as completed by krasserm** 2018-08-28 06:53 UTC
